apiVersion: v1
kind: Service
metadata:
    name: bicicletasfront
    labels:
        app: bicicletasfront
spec:
    ports:
        - port: 3000
          targetPort: http-server
          protocol: TCP
          nodePort: 30000
    selector:
        app: bicicletasfront
    type: LoadBalancer
